# Generated by Django 2.2.3 on 2020-02-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200221_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product_id',
            new_name='con_id',
        ),
    ]
