# Generated by Django 2.2.3 on 2020-02-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200221_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
