# Generated by Django 2.2.3 on 2020-03-02 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orders_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
