# Generated by Django 2.2.3 on 2020-03-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200301_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_json',
            new_name='items_json',
        ),
    ]
